backend/routes/web.php
<?php

use App\Models\Application;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
    // return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('users', App\Http\Controllers\UserController::class);


// Route::resource('reservations', App\Http\Controllers\ReservationController::class);


Route::resource('customers', App\Http\Controllers\CustomerController::class);
// Route::resource('api/customers', App\Http\Controllers\ApiCustomerController::class);


Route::resource('addresses', App\Http\Controllers\AddressController::class);
Route::resource('reservations', App\Http\Controllers\ReservationController::class);

Route::any('/sendmail', function () {
    mail('lkov@post.cz', 'Test', "Hello");
});


Route::resource('windows', App\Http\Controllers\WindowController::class);


Route::resource('applications', App\Http\Controllers\ApplicationController::class);

Route::get("iframe-test/{id}", function ($id) {
    $apps = Application::where('windowsID', $id)->get();
    // $apps = Application::where('windowsID','=',$id)->get();
    // dd($id);
    header("Content-Security-Policy: frame-ancestors 'self' " . join(', ', $apps->pluck('url')->toArray()));
    return view('iframe-test')->with('apps', $apps);
});


Route::resource('calendarExceptions', App\Http\Controllers\CalendarExceptionsController::class);

// Route::any('', function() {
//     return '';
// });


Route::resource('portalUsers', App\Http\Controllers\PortalUsersController::class);


Route::resource('roles', App\Http\Controllers\RoleController::class);

Route::get("calendar/test/{id}", function ($id) {
    return view('calendar-test')->with('id', $id);
});

backend/app/Models/PortalUsers.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class PortalUsers
 *
 * @package App\Models
 * @version April 27, 2022, 9:06 am UTC
 * @property \App\Models\Portal $portalsid
 * @property \App\Models\User $usersid
 * @property \App\Models\Role $roleid
 * @property integer $portalsID
 * @property integer $usersID
 * @property boolean $roleID
 * @property int $portalusersID
 * @property-read \App\Models\Portal $portals
 * @property-read \App\Models\User $users
 * @method static \Database\Factories\PortalUsersFactory factory(...$parameters)
 * @method static \Illuminate\Database\Eloquent\Builder|PortalUsers newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|PortalUsers newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|PortalUsers query()
 * @method static \Illuminate\Database\Eloquent\Builder|PortalUsers wherePortalsID($value)
 * @method static \Illuminate\Database\Eloquent\Builder|PortalUsers wherePortalusersID($value)
 * @method static \Illuminate\Database\Eloquent\Builder|PortalUsers whereRoleID($value)
 * @method static \Illuminate\Database\Eloquent\Builder|PortalUsers whereUsersID($value)
 * @mixin Model
 * @property-read \App\Models\Role $role
 */
class PortalUsers extends Model
{
    use HasFactory;

    public $table = 'portalusers';
    public $primaryKey = 'portalusersID';

    public $timestamps = false;


    public $fillable = [
        'portalsID',
        'usersID',
        'roleID'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'portalusersID' => 'integer',
        'portalsID' => 'integer',
        'usersID' => 'integer',
        'roleID' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'portalsID' => 'required|integer',
        'usersID' => 'required|integer',
        'roleID' => 'required|integer'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function portals()
    {
        return $this->belongsTo(\App\Models\Portal::class, 'portalsID');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function users()
    {
        return $this->belongsTo(\App\Models\User::class, 'usersID');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function role()
    {
        return $this->belongsTo(\App\Models\Role::class, 'roleID');
    }
}

backend/app/Http/Controllers/PortalUsersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreatePortalUsersRequest;
use App\Http\Requests\UpdatePortalUsersRequest;
use App\Repositories\PortalUsersRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class PortalUsersController extends AppBaseController
{
    /** @var PortalUsersRepository $portalUsersRepository*/
    private $portalUsersRepository;

    public function __construct(PortalUsersRepository $portalUsersRepo)
    {
        $this->portalUsersRepository = $portalUsersRepo;
    }

    /**
     * Display a listing of the PortalUsers.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $portalUsers = $this->portalUsersRepository->all();

        return view('portal_users.index')
            ->with('portalUsers', $portalUsers);
    }

    /**
     * Show the form for creating a new PortalUsers.
     *
     * @return Response
     */
    public function create()
    {
        return view('portal_users.create');
    }

    /**
     * Store a newly created PortalUsers in storage.
     *
     * @param CreatePortalUsersRequest $request
     *
     * @return Response
     */
    public function store(CreatePortalUsersRequest $request)
    {
        $input = $request->all();

        $portalUsers = $this->portalUsersRepository->create($input);

        Flash::success('Portal Users saved successfully.');

        return redirect(route('portalUsers.index'));
    }

    /**
     * Display the specified PortalUsers.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $portalUsers = $this->portalUsersRepository->find($id);

        if (empty($portalUsers)) {
            Flash::error('Portal Users not found');

            return redirect(route('portalUsers.index'));
        }

        return view('portal_users.show')->with('portalUsers', $portalUsers);
    }

    /**
     * Show the form for editing the specified PortalUsers.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $portalUsers = $this->portalUsersRepository->find($id);

        if (empty($portalUsers)) {
            Flash::error('Portal Users not found');

            return redirect(route('portalUsers.index'));
        }

        return view('portal_users.edit')->with('portalUsers', $portalUsers);
    }

    /**
     * Update the specified PortalUsers in storage.
     *
     * @param int $id
     * @param UpdatePortalUsersRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatePortalUsersRequest $request)
    {
        $portalUsers = $this->portalUsersRepository->find($id);

        if (empty($portalUsers)) {
            Flash::error('Portal Users not found');

            return redirect(route('portalUsers.index'));
        }

        $portalUsers = $this->portalUsersRepository->update($request->all(), $id);

        Flash::success('Portal Users updated successfully.');

        return redirect(route('portalUsers.index'));
    }

    /**
     * Remove the specified PortalUsers from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $portalUsers = $this->portalUsersRepository->find($id);

        if (empty($portalUsers)) {
            Flash::error('Portal Users not found');

            return redirect(route('portalUsers.index'));
        }

        $this->portalUsersRepository->delete($id);

        Flash::success('Portal Users deleted successfully.');

        return redirect(route('portalUsers.index'));
    }
}

backend/resources/views/portal_users/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Portal Users</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'portalUsers.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('portal_users.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('portalUsers.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

backend/resources/views/portal_users/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Portal Users</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($portalUsers, ['route' => ['portalUsers.update', $portalUsers->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('portal_users.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('portalUsers.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

backend/resources/views/portal_users/fields.blade.php
<!-- Portalsid Field -->
<div class="form-group col-sm-6">
    {!! Form::label('portalsID', 'Portalsid:') !!}
    {!! Form::number('portalsID', null, ['class' => 'form-control']) !!}
</div>

<!-- Usersid Field -->
<div class="form-group col-sm-6">
    {!! Form::label('usersID', 'Usersid:') !!}
    {!! Form::number('usersID', null, ['class' => 'form-control']) !!}
</div>

<!-- Roleid Field -->
<div class="form-group col-sm-6">
    <div class="form-check">
        {!! Form::hidden('roleID', 0, ['class' => 'form-check-input']) !!}
        {!! Form::checkbox('roleID', '1', null, ['class' => 'form-check-input']) !!}
        {!! Form::label('roleID', 'Roleid', ['class' => 'form-check-label']) !!}
    </div>
</div>

backend/resources/views/portal_users/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Portal Users</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('portalUsers.create') }}">
                        Add New
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('portal_users.table')

                <div class="card-footer clearfix">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

backend/resources/views/portal_users/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Portal Users Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('portalUsers.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('portal_users.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

backend/resources/views/portal_users/show_fields.blade.php
<!-- Portalsid Field -->
<div class="col-sm-12">
    {!! Form::label('portalsID', 'Portalsid:') !!}
    <p>{{ $portalUsers->portalsID }}</p>
</div>

<!-- Usersid Field -->
<div class="col-sm-12">
    {!! Form::label('usersID', 'Usersid:') !!}
    <p>{{ $portalUsers->usersID }}</p>
</div>

<!-- Roleid Field -->
<div class="col-sm-12">
    {!! Form::label('roleID', 'Roleid:') !!}
    <p>{{ $portalUsers->roleID }}</p>
</div>

backend/resources/views/portal_users/table.blade.php
<div class="table-responsive">
    <table class="table" id="portalUsers-table">
        <thead>
        <tr>
            <th>Portalsid</th>
        <th>Usersid</th>
        <th>Roleid</th>
            <th colspan="3">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($portalUsers as $portalUsers)
            <tr>
                <td>{{ $portalUsers->portalsID }}</td>
            <td>{{ $portalUsers->usersID }}</td>
            <td>{{ $portalUsers->roleID }}</td>
                <td width="120">
                    {!! Form::open(['route' => ['portalUsers.destroy', $portalUsers->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('portalUsers.show', [$portalUsers->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('portalUsers.edit', [$portalUsers->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>