backend/routes/web.php
<?php

use App\Models\Application;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
    // return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('users', App\Http\Controllers\UserController::class);


// Route::resource('reservations', App\Http\Controllers\ReservationController::class);


Route::resource('customers', App\Http\Controllers\CustomerController::class);
// Route::resource('api/customers', App\Http\Controllers\ApiCustomerController::class);


Route::resource('addresses', App\Http\Controllers\AddressController::class);
Route::resource('reservations', App\Http\Controllers\ReservationController::class);

Route::any('/sendmail', function () {
    mail('lkov@post.cz', 'Test', "Hello");
});


Route::resource('windows', App\Http\Controllers\WindowController::class);


Route::resource('applications', App\Http\Controllers\ApplicationController::class);

Route::get("iframe-test/{id}", function ($id) {
    $apps = Application::where('windowsID', $id)->get();
    // $apps = Application::where('windowsID','=',$id)->get();
    // dd($id);
    header("Content-Security-Policy: frame-ancestors 'self' " . join(', ', $apps->pluck('url')->toArray()));
    return view('iframe-test')->with('apps', $apps);
});


Route::resource('calendarExceptions', App\Http\Controllers\CalendarExceptionsController::class);

// Route::any('', function() {
//     return '';
// });


Route::resource('portalUsers', App\Http\Controllers\PortalUsersController::class);


Route::resource('roles', App\Http\Controllers\RoleController::class);

Route::get("calendar/test/{id}", function ($id) {
    return view('calendar-test')->with('id', $id);
});

backend/app/Models/CalendarExceptions.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class CalendarExceptions
 *
 * @package App\Models
 * @version April 17, 2022, 3:57 pm UTC
 * @property \App\Models\Window $windowsid
 * @property integer $windowsID
 * @property string $date_start
 * @property string $date_end
 * @property time $time_start
 * @property time $time_end
 * @property string $description
 * @property string $config
 * @property int $id
 * @property-read \App\Models\Window $windows
 * @method static \Database\Factories\CalendarExceptionsFactory factory(...$parameters)
 * @method static \Illuminate\Database\Eloquent\Builder|CalendarExceptions newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|CalendarExceptions newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|CalendarExceptions query()
 * @method static \Illuminate\Database\Eloquent\Builder|CalendarExceptions whereConfig($value)
 * @method static \Illuminate\Database\Eloquent\Builder|CalendarExceptions whereDateEnd($value)
 * @method static \Illuminate\Database\Eloquent\Builder|CalendarExceptions whereDateStart($value)
 * @method static \Illuminate\Database\Eloquent\Builder|CalendarExceptions whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|CalendarExceptions whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|CalendarExceptions whereTimeEnd($value)
 * @method static \Illuminate\Database\Eloquent\Builder|CalendarExceptions whereTimeStart($value)
 * @method static \Illuminate\Database\Eloquent\Builder|CalendarExceptions whereWindowsID($value)
 * @mixin Model
 */
class CalendarExceptions extends Model
{
    use HasFactory;

    public $table = 'calendars_exceptions';
    public $primaryKey = 'id';

    public $timestamps = false;


    public $fillable = [
        'windowsID',
        'date_start',
        'date_end',
        'time_start',
        'time_end',
        'description',
        'config'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'windowsID' => 'integer',
        'date_start' => 'date',
        'date_end' => 'date',
        'description' => 'string',
        'config' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'windowsID' => 'required|integer',
        'date_start' => 'required',
        'date_end' => 'required',
        'time_start' => 'nullable',
        'time_end' => 'nullable',
        'description' => 'nullable|string|max:8000',
        'config' => 'required|string'
    ];

    public function getConfigAttribute($value) {
        return json_decode($value);
    }

    public function setConfigAttribute($value) {
        $this->attributes['config'] = $value;
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function windows()
    {
        return $this->belongsTo(\App\Models\Window::class, 'windowsID');
    }
}

backend/app/Http/Controllers/CalendarExceptionsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateCalendarExceptionsRequest;
use App\Http\Requests\UpdateCalendarExceptionsRequest;
use App\Repositories\CalendarExceptionsRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class CalendarExceptionsController extends AppBaseController
{
    /** @var CalendarExceptionsRepository $calendarExceptionsRepository*/
    private $calendarExceptionsRepository;

    public function __construct(CalendarExceptionsRepository $calendarExceptionsRepo)
    {
        $this->calendarExceptionsRepository = $calendarExceptionsRepo;
    }

    /**
     * Display a listing of the CalendarExceptions.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $calendarExceptions = $this->calendarExceptionsRepository->all();

        return view('calendar_exceptions.index')
            ->with('calendarExceptions', $calendarExceptions);
    }

    /**
     * Show the form for creating a new CalendarExceptions.
     *
     * @return Response
     */
    public function create()
    {
        return view('calendar_exceptions.create');
    }

    /**
     * Store a newly created CalendarExceptions in storage.
     *
     * @param CreateCalendarExceptionsRequest $request
     *
     * @return Response
     */
    public function store(CreateCalendarExceptionsRequest $request)
    {
        $input = $request->all();

        $calendarExceptions = $this->calendarExceptionsRepository->create($input);

        Flash::success('Calendar Exceptions saved successfully.');

        return redirect(route('calendarExceptions.index'));
    }

    /**
     * Display the specified CalendarExceptions.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $calendarExceptions = $this->calendarExceptionsRepository->find($id);

        if (empty($calendarExceptions)) {
            Flash::error('Calendar Exceptions not found');

            return redirect(route('calendarExceptions.index'));
        }

        return view('calendar_exceptions.show')->with('calendarExceptions', $calendarExceptions);
    }

    /**
     * Show the form for editing the specified CalendarExceptions.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $calendarExceptions = $this->calendarExceptionsRepository->find($id);

        if (empty($calendarExceptions)) {
            Flash::error('Calendar Exceptions not found');

            return redirect(route('calendarExceptions.index'));
        }

        return view('calendar_exceptions.edit')->with('calendarExceptions', $calendarExceptions);
    }

    /**
     * Update the specified CalendarExceptions in storage.
     *
     * @param int $id
     * @param UpdateCalendarExceptionsRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCalendarExceptionsRequest $request)
    {
        $calendarExceptions = $this->calendarExceptionsRepository->find($id);

        if (empty($calendarExceptions)) {
            Flash::error('Calendar Exceptions not found');

            return redirect(route('calendarExceptions.index'));
        }

        $calendarExceptions = $this->calendarExceptionsRepository->update($request->all(), $id);

        Flash::success('Calendar Exceptions updated successfully.');

        return redirect(route('calendarExceptions.index'));
    }

    /**
     * Remove the specified CalendarExceptions from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $calendarExceptions = $this->calendarExceptionsRepository->find($id);

        if (empty($calendarExceptions)) {
            Flash::error('Calendar Exceptions not found');

            return redirect(route('calendarExceptions.index'));
        }

        $this->calendarExceptionsRepository->delete($id);

        Flash::success('Calendar Exceptions deleted successfully.');

        return redirect(route('calendarExceptions.index'));
    }
}

backend/resources/views/calendar_exceptions/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Calendar Exceptions</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'calendarExceptions.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('calendar_exceptions.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('calendarExceptions.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

backend/resources/views/calendar_exceptions/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Calendar Exceptions</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($calendarExceptions, ['route' => ['calendarExceptions.update', $calendarExceptions->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('calendar_exceptions.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('calendarExceptions.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

backend/resources/views/calendar_exceptions/fields.blade.php
<!-- Windowsid Field -->
<div class="form-group col-sm-6">
    {!! Form::label('windowsID', 'Windowsid:') !!}
    {!! Form::number('windowsID', null, ['class' => 'form-control']) !!}
</div>

<!-- Date Start Field -->
<div class="form-group col-sm-6">
    {!! Form::label('date_start', 'Date Start:') !!}
    {!! Form::text('date_start', null, ['class' => 'form-control','id'=>'date_start']) !!}
</div>

@push('page_scripts')
    <script type="text/javascript">
        $('#date_start').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- Date End Field -->
<div class="form-group col-sm-6">
    {!! Form::label('date_end', 'Date End:') !!}
    {!! Form::text('date_end', null, ['class' => 'form-control','id'=>'date_end']) !!}
</div>

@push('page_scripts')
    <script type="text/javascript">
        $('#date_end').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- Time Start Field -->
<div class="form-group col-sm-6">
    {!! Form::label('time_start', 'Time Start:') !!}
    {!! Form::text('time_start', null, ['class' => 'form-control']) !!}
</div>

<!-- Time End Field -->
<div class="form-group col-sm-6">
    {!! Form::label('time_end', 'Time End:') !!}
    {!! Form::text('time_end', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-6">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::text('description', null, ['class' => 'form-control','maxlength' => 8000,'maxlength' => 8000]) !!}
</div>

<!-- Config Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('config', 'Config:') !!}
    {!! Form::textarea('config', null, ['class' => 'form-control']) !!}
</div>

backend/resources/views/calendar_exceptions/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Calendar Exceptions</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('calendarExceptions.create') }}">
                        Add New
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('calendar_exceptions.table')

                <div class="card-footer clearfix">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

backend/resources/views/calendar_exceptions/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Calendar Exceptions Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('calendarExceptions.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('calendar_exceptions.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

backend/resources/views/calendar_exceptions/show_fields.blade.php
<!-- Windowsid Field -->
<div class="col-sm-12">
    {!! Form::label('windowsID', 'Windowsid:') !!}
    <p>{{ $calendarExceptions->windowsID }}</p>
</div>

<!-- Date Start Field -->
<div class="col-sm-12">
    {!! Form::label('date_start', 'Date Start:') !!}
    <p>{{ $calendarExceptions->date_start }}</p>
</div>

<!-- Date End Field -->
<div class="col-sm-12">
    {!! Form::label('date_end', 'Date End:') !!}
    <p>{{ $calendarExceptions->date_end }}</p>
</div>

<!-- Time Start Field -->
<div class="col-sm-12">
    {!! Form::label('time_start', 'Time Start:') !!}
    <p>{{ $calendarExceptions->time_start }}</p>
</div>

<!-- Time End Field -->
<div class="col-sm-12">
    {!! Form::label('time_end', 'Time End:') !!}
    <p>{{ $calendarExceptions->time_end }}</p>
</div>

<!-- Description Field -->
<div class="col-sm-12">
    {!! Form::label('description', 'Description:') !!}
    <p>{{ $calendarExceptions->description }}</p>
</div>

<!-- Config Field -->
<div class="col-sm-12">
    {!! Form::label('config', 'Config:') !!}
    <p>{{ $calendarExceptions->config }}</p>
</div>

backend/resources/views/calendar_exceptions/table.blade.php
<div class="table-responsive">
    <table class="table" id="calendarExceptions-table">
        <thead>
        <tr>
            <th>Windowsid</th>
        <th>Date Start</th>
        <th>Date End</th>
        <th>Time Start</th>
        <th>Time End</th>
        <th>Description</th>
        <th>Config</th>
            <th colspan="3">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($calendarExceptions as $calendarExceptions)
            <tr>
                <td>{{ $calendarExceptions->windowsID }}</td>
            <td>{{ $calendarExceptions->date_start }}</td>
            <td>{{ $calendarExceptions->date_end }}</td>
            <td>{{ $calendarExceptions->time_start }}</td>
            <td>{{ $calendarExceptions->time_end }}</td>
            <td>{{ $calendarExceptions->description }}</td>
            <td>{{ $calendarExceptions->config }}</td>
                <td width="120">
                    {!! Form::open(['route' => ['calendarExceptions.destroy', $calendarExceptions->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('calendarExceptions.show', [$calendarExceptions->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('calendarExceptions.edit', [$calendarExceptions->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>